name: Generate Sitemap and Ping Google

on:
  push:
    branches:
      - main  # or your deployment branch

jobs:
  sitemap:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install sitemap-generator-cli
        run: npm install -g sitemap-generator-cli

      - name: Generate sitemap from live site
        run: |
          sitemap-generator https://wildsweet.pages.dev/ --output ./sitemap.xml --maxDepth 10
          sed -i 's|https://wildsweet.pages.dev|https://wildsweet.co.uk|g' sitemap.xml

      - name: Setup Git Authentication
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git

      - name: Commit sitemap
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add sitemap.xml
          git diff --cached --quiet || git commit -m "Update sitemap"
          git push origin HEAD:${{ github.ref }}



      - name: Ping Google
        run: |
          curl "https://www.google.com/ping?sitemap=https://www.wildsweet.co.uk/sitemap.xml"

